### ISSUE TITLE
Where are you defining colors

### ISSUE THREAD

**Issue by sjsivert** [xmiah0906/dots#1]
Saw your post on r/unixporn and was very impressed with your blue colorscheme. I can not seem to find where you are setting your colors? You use variables in i3 config and "set_from_resource" but the xres files contains hardly any colors?

Thanks!

**Comment by xmiah0906** [comment]
I get coloscheme from [pywal](https://github.com/dylanaraps/pywal), and check color from $HOME/.cache/wal/colors.sh.

Enjoy ^___^
